apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-pubsub-demo-deployment
  labels:
    app: cloud-pubsub-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-pubsub-demo
  template:
    metadata:
      labels:
        app: cloud-pubsub-demo
    spec:
      containers:
        - name: cloud-pubsub-demo
          image: eu.gcr.io/learning-messaging/cloud-pubsub-demo:latest
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cloud-pubsub-demo
spec:
  type: NodePort
  selector:
    app: cloud-pubsub-demo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001