spring:
  application:
    name: cloud-pubsub-demo

  cloud:
    gcp:
      project-id: learning-messaging
      credentials:
        location: classpath:key.json

---

spring:
  profiles: local
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8085